Create table PUBLISH (
    PID INT(3) AUTO_INCREMENT,
    PUBLISHER_NAME VARCHAR(30) NOT NULL,
    CONSTRAINT UC_PUBLISHER_NAME UNIQUE (PUBLISHER_NAME),
    CONSTRAINT PK_GAMES PRIMARY KEY(PID)
);

Create table GAMES (
    GID INT(3) AUTO_INCREMENT,
    GAME_NAME VARCHAR(30) NOT NULL,
    PRICE INT(3) NOT NULL,
    STOCK INT(5) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    GAME_DESCRIPTION VARCHAR(200),
    PID INT(3) NOT NULL,
    CONSTRAINT UC_GAME_NAME UNIQUE (GAME_NAME),
    CONSTRAINT FK_GAMES FOREIGN KEY(PID) REFERENCES PUBLISH(PID),
    CONSTRAINT PK_GAMES PRIMARY KEY(GID),
    CONSTRAINT DF_GAMES CHECK (CONVERT(RELEASE_DATE, CHAR) LIKE "____-__-__")

);
 
Create table CLIENTS (
    CID INT(3) AUTO_INCREMENT,
    USRNME VARCHAR(20) NOT NULL,
    PASSWRD VARCHAR(20) NOT NULL,
    isADM TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT PK_CLIENTS PRIMARY KEY(CID),
    CONSTRAINT UC_USRNME UNIQUE (USRNME),
    CONSTRAINT UAN_CLIENTS CHECK (USRNME REGEXP '^[a-zA-Z0-9]+$'),
    CONSTRAINT PAN_CLIENTS CHECK (PASSWRD REGEXP '^[a-zA-Z0-9]+$')    
);

Create table CONTACT (
    CID INT(3),
    PNUMBER CHAR(10) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_CONTACTS FOREIGN KEY(CID) REFERENCES CLIENTS(CID),
    CONSTRAINT EM_CONTACTS CHECK (EMAIL LIKE '%@%.%'),
    CONSTRAINT PN_CONTACTS CHECK (PNUMBER REGEXP '07[0-9]{8}')
);

Create table ORDERS (
    ORID INT(3) AUTO_INCREMENT,
    CID INT(3),
    GID INT(3),
    CONSTRAINT PK_ORDERS PRIMARY KEY(ORID),
    CONSTRAINT FK_C_ORDERS FOREIGN KEY(CID) REFERENCES CLIENTS(CID),
    CONSTRAINT FK_g_ORDERS FOREIGN KEY(GID) REFERENCES GAMES(GID)
);